export const AliceBlue = '#F0F8FF'
export const Azure = '#F0FFFF'
export const MediumSlateBlue = '#7B68EE'
export const LightBlue = '#ADD8E6'
export const LightSkyBlue = '#87CEFA'
export const Red = '#FF0000'
export const Lime = '#00FF00'
export const DeepSkyBlue = '#00BFFF'